namespace :payments do
  namespace :import do

    task :tasks do
      Rake.invoke_task 'payments:source:___ids:insert', 'UNDELETABLE'
      Rake.invoke_task 'payments:source:payments:add___row_id'
      Rake.invoke_task 'payments:source:payments:update___row_id'
      Rake.invoke_task 'payments:source:payments:add___paycard_id'
      Rake.invoke_task 'payments:source:payments:update___paycard_id'
      Rake.invoke_task 'payments:source:payments:update_obligationtype_id'
      Rake.invoke_task 'payments:source:payments:update___paycard_id2'
      Rake.invoke_task 'payments:source:payments:add___type'
      Rake.invoke_task 'payments:source:payments:update___type'
      Rake.invoke_task 'payments:source:payments:add___object'
      Rake.invoke_task 'payments:source:payments:update___object'
      Rake.invoke_task 'payments:source:payments:add___baccount'
      Rake.invoke_task 'payments:source:payments:update___baccount'
      Rake.invoke_task 'payments:source:payments:add___bcorr'
      Rake.invoke_task 'payments:source:payments:update___bcorr'
      Rake.invoke_task 'payments:source:payments:add___income_code'
      Rake.invoke_task 'payments:source:payments:update___income_code'
      Rake.invoke_task 'payments:source:payments:add___income'
      Rake.invoke_task 'payments:source:payments:update___income'
      Rake.invoke_task 'payments:destination:rem1:disable_trigger_rem1_insert_entry'
      Rake.invoke_task 'payments:destination:entry:insert'
      Rake.invoke_task 'payments:source:payments:add___entry'
      Rake.invoke_task 'payments:source:payments:update___entry'
      Rake.invoke_task 'payments:destination:rem1:insert'
      Rake.invoke_task 'payments:source:payments:add___rem1'
      Rake.invoke_task 'payments:source:payments:update___rem1'
      Rake.invoke_task 'payments:destination:t_rem1:insert'
      Rake.invoke_task 'payments:destination:rem1:enable_trigger_rem1_insert_entry'
      Rake.invoke_task 'payments:destination:rem2:insert'
      Rake.invoke_task 'payments:source:payments:add___rem2'
      Rake.invoke_task 'payments:source:payments:update___rem2'
      Rake.invoke_task 'payments:source:payments:add___rem3'
      Rake.invoke_task 'payments:destination:rem3:insert'
      Rake.invoke_task 'payments:source:payments:update___rem3'
      Rake.invoke_task 'payments:destination:extrem:insert'
      Rake.invoke_task 'payments:source:payments:add___extrem'
      Rake.invoke_task 'payments:source:payments:update___extrem'
      Rake.invoke_task 'payments:destination:t_charge:insert'
      #Rake.invoke_task 'payments:source:___ids:update_link'
    end

  end
end
